// <auto-generated />
namespace SMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class update_announcement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_announcement));
        
        string IMigrationMetadata.Id
        {
            get { return "202208080644592_update_announcement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
