// <auto-generated />
namespace SMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class status_addded_inuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(status_addded_inuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202208220959484_status_addded_inuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
