// <auto-generated />
namespace SMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Announcementsubject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Announcementsubject));
        
        string IMigrationMetadata.Id
        {
            get { return "202208021022393_Announcement-subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
